/**
 * README Generator
 *
 * Generates a deployment README with prerequisites, deployment commands,
 * architecture overview, and parameter descriptions.
 */

import type { Architecture } from '../schema/types.js';
import type { IaCExportOptions, IaCExportResult, GeneratedFile } from './types.js';

export function generateReadme(
  arch: Architecture,
  options: IaCExportOptions,
  result: IaCExportResult,
): GeneratedFile {
  const isBicep = options.format === 'bicep';
  const envs = options.environments.map(e =>
    e === 'production' ? 'prod' : e === 'development' ? 'dev' : 'staging'
  );

  const lines: string[] = [];

  // Title
  lines.push(`# ${arch.title || 'Infrastructure Deployment'}`);
  lines.push('');
  if (arch.description) {
    lines.push(`> ${arch.description}`);
    lines.push('');
  }
  lines.push(`Generated by **AI Architecture Generator** — ${isBicep ? 'Bicep' : 'Terraform'} with Azure Verified Modules (AVM).`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Format | ${isBicep ? 'Bicep' : 'Terraform'} |`);
  lines.push(`| Total files | ${result.summary.totalFiles} |`);
  lines.push(`| Resources | ${result.summary.resourceCount} |`);
  lines.push(`| Modules | ${result.summary.moduleCount} |`);
  lines.push(`| Environments | ${envs.join(', ')} |`);
  if (options.useAVM) {
    lines.push('| Azure Verified Modules | ✅ Enabled |');
  }
  lines.push('');

  // Prerequisites
  lines.push('## Prerequisites');
  lines.push('');
  lines.push('1. **Azure CLI** — [Install](https://learn.microsoft.com/cli/azure/install-azure-cli)');
  lines.push('   ```bash');
  lines.push('   az login');
  lines.push('   az account set --subscription "<your-subscription-id>"');
  lines.push('   ```');
  lines.push('');

  if (isBicep) {
    lines.push('2. **Bicep CLI** — included with Azure CLI v2.20+');
    lines.push('   ```bash');
    lines.push('   az bicep install');
    lines.push('   az bicep version');
    lines.push('   ```');
  } else {
    lines.push('2. **Terraform** >= 1.9.0 — [Install](https://developer.hashicorp.com/terraform/install)');
    lines.push('   ```bash');
    lines.push('   terraform version');
    lines.push('   ```');
  }
  lines.push('');
  lines.push('3. **Azure permissions** — Contributor role on the target subscription');
  lines.push('');

  // File structure
  lines.push('## File Structure');
  lines.push('');
  lines.push('```');
  for (const f of result.files) {
    if (f.path === 'README.md') continue;
    lines.push(`├── ${f.path}`);
  }
  lines.push('```');
  lines.push('');

  // Deployment
  lines.push('## Deployment');
  lines.push('');

  if (isBicep) {
    for (const env of envs) {
      lines.push(`### ${capitalize(env)}`);
      lines.push('');
      lines.push('```bash');
      lines.push(`# Validate`);
      lines.push(`az deployment sub validate \\`);
      lines.push(`  --location westeurope \\`);
      lines.push(`  --template-file main.bicep \\`);
      lines.push(`  --parameters main.${env}.bicepparam`);
      lines.push('');
      lines.push(`# Deploy`);
      lines.push(`az deployment sub create \\`);
      lines.push(`  --location westeurope \\`);
      lines.push(`  --template-file main.bicep \\`);
      lines.push(`  --parameters main.${env}.bicepparam`);
      lines.push('```');
      lines.push('');
    }

    lines.push('### What-If (Preview Changes)');
    lines.push('');
    lines.push('```bash');
    lines.push('az deployment sub what-if \\');
    lines.push('  --location westeurope \\');
    lines.push(`  --template-file main.bicep \\`);
    lines.push(`  --parameters main.${envs[0]}.bicepparam`);
    lines.push('```');
  } else {
    lines.push('### Initialize');
    lines.push('');
    lines.push('```bash');
    lines.push('terraform init');
    lines.push('```');
    lines.push('');

    for (const env of envs) {
      lines.push(`### ${capitalize(env)}`);
      lines.push('');
      lines.push('```bash');
      lines.push(`# Plan`);
      lines.push(`terraform plan -var-file=environments/${env}.tfvars -out=${env}.tfplan`);
      lines.push('');
      lines.push(`# Apply`);
      lines.push(`terraform apply ${env}.tfplan`);
      lines.push('```');
      lines.push('');
    }

    lines.push('### Destroy');
    lines.push('');
    lines.push('```bash');
    lines.push(`terraform destroy -var-file=environments/${envs[0]}.tfvars`);
    lines.push('```');
  }
  lines.push('');

  // Parameters
  lines.push('## Parameters');
  lines.push('');
  lines.push('| Parameter | Description | Default |');
  lines.push('|-----------|-------------|---------|');
  lines.push('| `location` | Primary Azure region | `westeurope` |');
  lines.push('| `environment` | Environment name (dev/staging/prod) | `dev` |');
  lines.push('| `prefix` | Resource name prefix | `""` |');
  lines.push('| `tags` | Tags to apply to all resources | see file |');
  if (!isBicep) {
    lines.push('| `subscription_id` | Azure subscription ID | — |');
  }
  lines.push('');

  // Azure Verified Modules note
  if (options.useAVM) {
    lines.push('## Azure Verified Modules');
    lines.push('');
    lines.push('This deployment uses [Azure Verified Modules (AVM)](https://azure.github.io/Azure-Verified-Modules/) where available.');
    lines.push('AVM provides Microsoft-maintained, well-tested infrastructure modules with:');
    lines.push('');
    lines.push('- ✅ Consistent naming and tagging');
    lines.push('- ✅ Built-in diagnostics settings');
    lines.push('- ✅ RBAC role assignments');
    lines.push('- ✅ Private endpoint support');
    lines.push('- ✅ Resource locks');
    lines.push('');
    lines.push('Resources without an AVM module are deployed using raw resource declarations marked with `// TODO` comments.');
    lines.push('');
  }

  // CI/CD
  if (options.includePipeline) {
    lines.push('## CI/CD');
    lines.push('');
    if (options.includePipeline === 'github-actions') {
      lines.push('A GitHub Actions workflow is included. Configure these repository secrets:');
      lines.push('');
      lines.push('- `AZURE_CLIENT_ID` — Service principal / managed identity client ID');
      lines.push('- `AZURE_TENANT_ID` — Azure AD tenant ID');
      lines.push('- `AZURE_SUBSCRIPTION_ID` — Target subscription ID');
      lines.push('');
      lines.push('Use [federated credentials](https://learn.microsoft.com/entra/workload-id/workload-identity-federation) for passwordless authentication.');
    } else {
      lines.push('An Azure DevOps pipeline is included. Create a service connection named `AzureServiceConnection`.');
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [AI Architecture Generator](https://github.com/your-org/ai-architecture-generator)*');

  return {
    path: 'README.md',
    content: lines.join('\n'),
    description: 'Deployment guide with prerequisites, commands, and parameter reference',
  };
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
