/**
 * Terraform Generator
 *
 * Generates a complete set of Terraform (.tf) files from an Architecture
 * object, using Azure Verified Modules where available.
 */

import type { Architecture } from '../../schema/types.js';
import type { IaCExportOptions, GeneratedFile, IaCExportResult, IaCResource, IaCModule } from '../types.js';
import { mapArchitectureToResources, groupResourcesIntoModules } from '../resource-mapper.js';
import { AVM_TERRAFORM_MODULES, AZURERM_FALLBACK_RESOURCES, hasAvmTerraformModule } from './avm-registry.js';

export function generateTerraform(arch: Architecture, options: IaCExportOptions): IaCExportResult {
  const resources = mapArchitectureToResources(arch);
  const modules = groupResourcesIntoModules(resources);

  const files: GeneratedFile[] = [];
  let resourceCount = 0;
  let moduleCount = 0;

  // 1. main.tf — providers + module calls
  files.push({
    path: 'main.tf',
    content: generateMainTf(arch, modules, options),
    description: 'Main Terraform configuration — provider config and module calls',
  });

  // 2. variables.tf
  files.push({
    path: 'variables.tf',
    content: generateVariablesTf(arch, modules),
    description: 'Input variable declarations',
  });

  // 3. outputs.tf
  files.push({
    path: 'outputs.tf',
    content: generateOutputsTf(modules),
    description: 'Output value declarations',
  });

  // 4. Module directories
  for (const mod of modules) {
    files.push({
      path: `modules/${mod.name}/main.tf`,
      content: generateModuleMainTf(mod, options),
      description: `${capitalize(mod.name)} module — ${mod.resources.length} resource(s)`,
    });
    files.push({
      path: `modules/${mod.name}/variables.tf`,
      content: generateModuleVariablesTf(mod),
      description: `${capitalize(mod.name)} module variables`,
    });
    files.push({
      path: `modules/${mod.name}/outputs.tf`,
      content: generateModuleOutputsTf(mod),
      description: `${capitalize(mod.name)} module outputs`,
    });
    resourceCount += mod.resources.length;
    moduleCount++;
  }

  // 5. terraform.tfvars for each environment
  for (const env of options.environments) {
    files.push({
      path: `environments/${envShort(env)}.tfvars`,
      content: generateTfvars(env, arch),
      description: `Variable values for ${env} environment`,
    });
  }

  // 6. backend.tf
  files.push({
    path: 'backend.tf',
    content: generateBackendTf(),
    description: 'Backend configuration for remote state',
  });

  // 7. CI/CD pipeline
  if (options.includePipeline === 'github-actions') {
    files.push({
      path: '.github/workflows/deploy-terraform.yml',
      content: generateGitHubActionsTf(options),
      description: 'GitHub Actions workflow for Terraform deployment',
    });
  } else if (options.includePipeline === 'azure-devops') {
    files.push({
      path: 'azure-pipelines.yml',
      content: generateAzureDevOpsTf(options),
      description: 'Azure DevOps pipeline for Terraform deployment',
    });
  }

  return {
    files,
    summary: {
      totalFiles: files.length,
      resourceCount,
      moduleCount,
      format: 'terraform',
    },
  };
}

// ─── main.tf ──────────────────────────────────────────────────────

function generateMainTf(arch: Architecture, modules: IaCModule[], options: IaCExportOptions): string {
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push(`# ${arch.title || 'Architecture Deployment'}`);
  lines.push(`# ${arch.description || 'Generated by AI Architecture Generator'}`);
  lines.push('# ==========================================');
  lines.push('');
  lines.push('terraform {');
  lines.push('  required_version = ">= 1.11.0"');
  lines.push('');
  lines.push('  required_providers {');
  lines.push('    azurerm = {');
  lines.push('      source  = "hashicorp/azurerm"');
  lines.push('      version = "~> 4.0"');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('provider "azurerm" {');
  lines.push('  features {}');
  lines.push('  subscription_id = var.subscription_id');
  lines.push('}');
  lines.push('');

  // Resource Group
  lines.push('# Resource Group');
  lines.push('resource "azurerm_resource_group" "main" {');
  lines.push('  name     = "rg-${var.prefix}${var.environment}"');
  lines.push('  location = var.location');
  lines.push('  tags     = var.tags');
  lines.push('}');
  lines.push('');

  // Module calls
  for (const mod of modules) {
    const depModules = mod.dependsOnModules.filter(d => modules.some(m => m.name === d));

    lines.push(`# ${capitalize(mod.name)}`);
    lines.push(`module "${mod.name}" {`);
    lines.push(`  source = "./modules/${mod.name}"`);
    lines.push('');
    lines.push('  resource_group_name = azurerm_resource_group.main.name');
    lines.push('  location            = var.location');
    lines.push('  environment         = var.environment');
    lines.push('  prefix              = var.prefix');
    lines.push('  tags                = var.tags');

    // Don't pass dependency outputs as variables — modules don't declare them
    // Dependencies are handled via depends_on only
    // Pass subscription_id if any module resource uses parent_id
    const hasParentIdResource = mod.resources.some(r => {
      const avmRef = AVM_TERRAFORM_MODULES[r.resourceType];
      return avmRef && avmRef.requiredVars.includes('parent_id');
    });
    if (hasParentIdResource) {
      lines.push('  subscription_id = var.subscription_id');
    }

    lines.push('');
    if (depModules.length > 0) {
      lines.push(`  depends_on = [${depModules.map(d => `module.${d}`).join(', ')}]`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── variables.tf ─────────────────────────────────────────────────

function generateVariablesTf(arch: Architecture, modules: IaCModule[]): string {
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# Input Variables');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('variable "subscription_id" {');
  lines.push('  description = "Azure subscription ID"');
  lines.push('  type        = string');
  lines.push('}');
  lines.push('');

  lines.push('variable "location" {');
  lines.push('  description = "Primary deployment region"');
  lines.push('  type        = string');
  lines.push('  default     = "westeurope"');
  lines.push('}');
  lines.push('');

  lines.push('variable "environment" {');
  lines.push('  description = "Environment name (dev, staging, prod)"');
  lines.push('  type        = string');
  lines.push('  default     = "dev"');
  lines.push('');
  lines.push('  validation {');
  lines.push('    condition     = contains(["dev", "staging", "prod"], var.environment)');
  lines.push('    error_message = "Environment must be dev, staging, or prod."');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('variable "prefix" {');
  lines.push('  description = "Resource name prefix"');
  lines.push('  type        = string');
  lines.push('  default     = ""');
  lines.push('}');
  lines.push('');

  lines.push('variable "tags" {');
  lines.push('  description = "Tags to apply to all resources"');
  lines.push('  type        = map(string)');
  lines.push('  default = {');
  lines.push(`    project    = "${arch.title || 'architecture'}"`);
  lines.push('    managed_by = "terraform"');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ─── outputs.tf ───────────────────────────────────────────────────

function generateOutputsTf(modules: IaCModule[]): string {
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# Outputs');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('output "resource_group_name" {');
  lines.push('  description = "Name of the resource group"');
  lines.push('  value       = azurerm_resource_group.main.name');
  lines.push('}');
  lines.push('');

  lines.push('output "resource_group_id" {');
  lines.push('  description = "ID of the resource group"');
  lines.push('  value       = azurerm_resource_group.main.id');
  lines.push('}');
  lines.push('');

  for (const mod of modules) {
    // Filter out subnet outputs
    const effectiveOutputs = mod.outputs.filter(out => {
      const subnetRes = mod.resources.find(r => r.resourceType === 'subnet' && out.name.startsWith(r.identifier));
      return !subnetRes;
    });
    for (const out of effectiveOutputs.slice(0, 3)) {
      lines.push(`output "${mod.name}_${out.name}" {`);
      lines.push(`  description = "${out.description}"`);
      lines.push(`  value       = module.${mod.name}.${out.name}`);
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ─── Module main.tf ───────────────────────────────────────────────

function generateModuleMainTf(mod: IaCModule, options: IaCExportOptions): string {
  const lines: string[] = [];

  // Filter out subnet resources — they should be inlined in VNet definitions
  const effectiveResources = mod.resources.filter(r => r.resourceType !== 'subnet');

  lines.push(`# ==========================================`);
  lines.push(`# ${capitalize(mod.name)} Module`);
  lines.push(`# ==========================================`);
  lines.push('');

  // Add data source for tenant_id if needed (e.g., Key Vault)
  const needsTenantId = effectiveResources.some(r => r.resourceType === 'keyVault');
  if (needsTenantId) {
    lines.push('data "azurerm_client_config" "current" {}');
    lines.push('');
  }

  for (const r of effectiveResources) {
    lines.push(`# ${r.name}`);

    if (options.useAVM && hasAvmTerraformModule(r.resourceType)) {
      lines.push(...generateAvmModuleCallTf(r));
    } else {
      lines.push(...generateRawResourceTf(r));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateAvmModuleCallTf(r: IaCResource): string[] {
  const lines: string[] = [];
  const avmRef = AVM_TERRAFORM_MODULES[r.resourceType]!;

  // Some AVM modules use parent_id instead of resource_group_name
  const usesParentId = avmRef.requiredVars.includes('parent_id');

  lines.push(`module "${r.identifier}" {`);
  lines.push(`  source  = "${avmRef.source}"`);
  lines.push(`  version = "${avmRef.version}"`);
  lines.push('');
  lines.push(`  name                = "\${var.prefix}${r.iacName}-\${var.environment}"`);

  if (avmRef.requiredVars.includes('location')) {
    lines.push('  location            = var.location');
  }
  if (usesParentId) {
    lines.push('  parent_id           = "/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}"');
  } else if (avmRef.requiredVars.includes('resource_group_name')) {
    lines.push('  resource_group_name = var.resource_group_name');
  }

  // Type-specific params
  generateTfTypeSpecificParams(r, lines);

  lines.push('  tags = var.tags');
  lines.push('}');

  return lines;
}

function generateTfTypeSpecificParams(r: IaCResource, lines: string[]): void {
  switch (r.resourceType) {
    case 'vm':
      lines.push('  os_type = "Linux"');
      lines.push('  zone    = 1');
      lines.push('');
      lines.push('  network_interfaces = {');
      lines.push('    primary = {');
      lines.push('      name = "nic-${var.prefix}' + r.iacName + '-${var.environment}"');
      lines.push('      ip_configurations = {');
      lines.push('        default = {');
      lines.push('          name                          = "ipconfig1"');
      lines.push('          private_ip_subnet_resource_id = "" # TODO: Reference subnet');
      lines.push('        }');
      lines.push('      }');
      lines.push('    }');
      lines.push('  }');
      break;
    case 'aks':
      lines.push('  default_node_pool = {');
      lines.push('    name       = "system"');
      lines.push('    vm_size    = "Standard_D4s_v5"');
      lines.push('    node_count = 3');
      lines.push('  }');
      break;
    case 'vnet':
    case 'hubVnet': {
      const addressSpace = r.addressSpace || r.properties?.addressSpace as string || '10.0.0.0/16';
      lines.push(`  address_space = ["${addressSpace}"]`);
      lines.push('');

      const subnets = r.architectureSubnets;
      if (subnets && subnets.length > 0) {
        lines.push('  subnets = {');
        for (const s of subnets) {
          const prefix = s.addressPrefix || guessSubnetPrefix(addressSpace, subnets.indexOf(s));
          const key = s.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
          lines.push(`    ${key} = {`);
          lines.push(`      name             = "${s.name}"`);
          lines.push(`      address_prefixes = ["${prefix}"]`);
          lines.push('    }');
        }
        lines.push('  }');
      } else {
        const base = addressSpace.split('/')[0].split('.').slice(0, 2).join('.');
        lines.push('  subnets = {');
        lines.push('    default = {');
        lines.push('      name             = "default"');
        lines.push(`      address_prefixes = ["${base}.0.0/24"]`);
        lines.push('    }');
        lines.push('  }');
      }
      break;
    }
    case 'storageAccount':
      lines.push('  account_tier             = "Standard"');
      lines.push('  account_replication_type = "LRS"');
      break;
    case 'keyVault':
      lines.push('  tenant_id = data.azurerm_client_config.current.tenant_id');
      // AVM Key Vault module uses RBAC by default, no enable_rbac_authorization param
      break;
    case 'openAI':
      lines.push('  kind     = "OpenAI"');
      lines.push('  sku_name = "S0"');
      break;
    case 'cognitiveServices':
      lines.push('  kind     = "CognitiveServices"');
      lines.push('  sku_name = "S0"');
      break;
    case 'cosmosDb':
      // AVM Cosmos module doesn't have kind/offer_type — uses geo_locations and consistency_policy
      lines.push('  geo_locations = [{');
      lines.push('    location          = var.location');
      lines.push('    failover_priority = 0');
      lines.push('  }]');
      break;
    case 'redis':
      lines.push('  sku_name = "Standard"');
      lines.push('  capacity = 1');
      // AVM Redis module doesn't have family param — it's inferred from sku_name
      break;
    case 'logAnalytics':
      lines.push('  log_analytics_workspace_sku            = "PerGB2018"');
      lines.push('  log_analytics_workspace_retention_in_days = 30');
      break;
    case 'containerAppEnv':
      // AVM module uses log_analytics_workspace object, not log_analytics_workspace_id
      lines.push('  # log_analytics_workspace = { id = module.monitoring.law_id } # TODO: Reference log analytics workspace');
      break;
    case 'containerApp':
      lines.push('  container_app_environment_resource_id = "" # TODO: Reference Container App Environment');
      lines.push('  template = {');
      lines.push('    containers = [{');
      lines.push('      name   = "main"');
      lines.push('      image  = "mcr.microsoft.com/k8se/quickstart:latest"');
      lines.push('      cpu    = 0.25');
      lines.push('      memory = "0.5Gi"');
      lines.push('    }]');
      lines.push('  }');
      break;
    case 'appService':
      lines.push('  os_type              = "Linux"');
      lines.push('  kind                 = "webapp"');
      lines.push('  service_plan_resource_id = "" # TODO: Reference App Service Plan resource ID');
      break;
    case 'functionApp':
      lines.push('  os_type              = "Linux"');
      lines.push('  kind                 = "functionapp"');
      lines.push('  service_plan_resource_id = "" # TODO: Reference App Service Plan resource ID');
      break;
    case 'appServicePlan':
      lines.push('  os_type  = "Linux"');
      lines.push('  sku_name = "B1"');
      break;
    case 'apiManagement':
      lines.push('  publisher_email = "admin@contoso.com" # TODO: Update');
      lines.push('  publisher_name  = "Contoso" # TODO: Update');
      lines.push('  sku_name        = "Developer_1"');
      break;
    case 'sqlServer':
      lines.push('  server_version = "12.0"');
      break;
    case 'loadBalancer':
      lines.push('  frontend_ip_configurations = {');
      lines.push('    default = {');
      lines.push('      name = "frontend"');
      lines.push('    }');
      lines.push('  }');
      break;
    case 'vmss':
      // VMSS AVM module has very different interface — leave minimal
      break;
    case 'firewall':
      lines.push('  firewall_sku_tier = "Standard"');
      lines.push('  firewall_sku_name = "AZFW_VNet"');
      break;
    case 'serviceBus':
      lines.push('  sku = "Standard"');
      break;
    case 'databricks':
      lines.push('  sku = "premium"');
      break;
  }
}

function generateRawResourceTf(r: IaCResource): string[] {
  const lines: string[] = [];
  const azurermType = AZURERM_FALLBACK_RESOURCES[r.resourceType] || `azurerm_${r.resourceType.toLowerCase()}`;

  // Some resource types don't support location/tags at top level
  const isChildResource = r.resourceType === 'subnet';

  lines.push(`# TODO: AVM module not yet available for ${r.resourceType} — using raw resource`);
  lines.push(`resource "${azurermType}" "${r.identifier}" {`);
  lines.push(`  name                = "\${var.prefix}${r.iacName}-\${var.environment}"`);
  if (!isChildResource) {
    lines.push('  location            = var.location');
  }
  lines.push('  resource_group_name = var.resource_group_name');

  // Type-specific required properties for raw resources
  switch (r.resourceType) {
    case 'vpnGateway':
      lines.push('  type = "Vpn"');
      lines.push('  sku  = "VpnGw1AZ"');
      lines.push('');
      lines.push('  ip_configuration {');
      lines.push('    name                 = "default"');
      lines.push('    public_ip_address_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.Network/publicIPAddresses/pip-placeholder" # TODO: Reference Public IP');
      lines.push('    subnet_id            = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet" # TODO: Reference GatewaySubnet ID');
      lines.push('  }');
      break;
    case 'subnet':
      lines.push('  virtual_network_name = "" # TODO: Reference VNet name');
      lines.push('  address_prefixes     = ["10.0.0.0/24"] # TODO: Set correct prefix');
      break;
    case 'localNetworkGateway':
      lines.push('  gateway_address = "" # TODO: Set on-premises gateway IP');
      break;
    case 'connection':
      lines.push('  type                       = "IPsec"');
      lines.push('  virtual_network_gateway_id = "" # TODO: Reference VPN Gateway ID');
      lines.push('  local_network_gateway_id   = "" # TODO: Reference Local Network Gateway ID');
      lines.push('  shared_key                 = "" # TODO: Set shared key');
      break;
  }

  if (!isChildResource) {
    lines.push('  tags                = var.tags');
  }
  lines.push('}');

  return lines;
}

// ─── Module variables.tf ──────────────────────────────────────────

function generateModuleVariablesTf(mod: IaCModule): string {
  const lines: string[] = [];

  lines.push('variable "resource_group_name" {');
  lines.push('  description = "Name of the resource group"');
  lines.push('  type        = string');
  lines.push('}');
  lines.push('');
  lines.push('variable "location" {');
  lines.push('  description = "Deployment region"');
  lines.push('  type        = string');
  lines.push('}');
  lines.push('');
  lines.push('variable "environment" {');
  lines.push('  description = "Environment name"');
  lines.push('  type        = string');
  lines.push('}');
  lines.push('');
  lines.push('variable "prefix" {');
  lines.push('  description = "Resource name prefix"');
  lines.push('  type        = string');
  lines.push('  default     = ""');
  lines.push('}');
  lines.push('');
  lines.push('variable "tags" {');
  lines.push('  description = "Tags to apply to resources"');
  lines.push('  type        = map(string)');
  lines.push('  default     = {}');
  lines.push('}');
  lines.push('');

  // Add subscription_id if any resource uses parent_id
  const hasParentIdResource = mod.resources.some(r => {
    const avmRef = AVM_TERRAFORM_MODULES[r.resourceType];
    return avmRef && avmRef.requiredVars.includes('parent_id');
  });
  if (hasParentIdResource) {
    lines.push('variable "subscription_id" {');
    lines.push('  description = "Azure subscription ID"');
    lines.push('  type        = string');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Module outputs.tf ────────────────────────────────────────────

function generateModuleOutputsTf(mod: IaCModule): string {
  const lines: string[] = [];

  // Filter out subnet outputs — subnets are inlined in VNet
  const effectiveOutputs = mod.outputs.filter(out => {
    const subnetRes = mod.resources.find(r => r.resourceType === 'subnet' && out.name.startsWith(r.identifier));
    return !subnetRes;
  });

  for (const out of effectiveOutputs) {
    lines.push(`output "${out.name}" {`);
    lines.push(`  description = "${out.description}"`);

    // For AVM modules, output comes from the module
    const r = mod.resources.find(res => out.name.startsWith(res.identifier));
    if (r && hasAvmTerraformModule(r.resourceType)) {
      lines.push(`  value       = module.${r.identifier}.resource_id`);
    } else if (r) {
      const azurermType = AZURERM_FALLBACK_RESOURCES[r.resourceType] || `azurerm_${r.resourceType.toLowerCase()}`;
      lines.push(`  value       = ${azurermType}.${r.identifier}.id`);
    } else {
      lines.push('  value       = "" # TODO: Set output value');
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── tfvars ───────────────────────────────────────────────────────

function generateTfvars(env: string, arch: Architecture): string {
  const profile = ENV_SIZES[env] || ENV_SIZES.development;
  const lines: string[] = [];

  lines.push(`# ${capitalize(env)} environment variables`);
  lines.push(`# Generated by AI Architecture Generator`);
  lines.push('');
  lines.push(`subscription_id = "" # TODO: Set your subscription ID`);
  lines.push(`location        = "${profile.location}"`);
  lines.push(`environment     = "${profile.shortName}"`);
  lines.push(`prefix          = ""`);
  lines.push('');
  lines.push('tags = {');
  lines.push(`  environment = "${profile.shortName}"`);
  lines.push(`  project     = "${arch.title || 'architecture'}"`);
  lines.push('  managed_by  = "terraform"');
  lines.push('}');

  return lines.join('\n');
}

const ENV_SIZES: Record<string, { shortName: string; location: string }> = {
  production: { shortName: 'prod', location: 'westeurope' },
  development: { shortName: 'dev', location: 'westeurope' },
  staging: { shortName: 'staging', location: 'westeurope' },
};

// ─── backend.tf ───────────────────────────────────────────────────

function generateBackendTf(): string {
  return `# ==========================================
# Backend Configuration
# ==========================================
# Uncomment and configure for remote state storage.
#
# terraform {
#   backend "azurerm" {
#     resource_group_name  = "rg-terraform-state"
#     storage_account_name = "stterraformstate"
#     container_name       = "tfstate"
#     key                  = "infrastructure.tfstate"
#   }
# }
`;
}

// ─── CI/CD Pipelines ──────────────────────────────────────────────

function generateGitHubActionsTf(options: IaCExportOptions): string {
  const envs = options.environments.map(e => envShort(e));
  return `name: Deploy Terraform Infrastructure
on:
  push:
    branches: [main]
    paths:
      - '**.tf'
      - '**.tfvars'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: '${envs[0]}'
        type: choice
        options:
${envs.map(e => `          - ${e}`).join('\n')}

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -var-file=environments/\${{ inputs.environment || '${envs[0]}' }}.tfvars -out=tfplan
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: \${{ inputs.environment || '${envs[0]}' }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
`;
}

function generateAzureDevOpsTf(options: IaCExportOptions): string {
  const envs = options.environments.map(e => envShort(e));
  return `trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**.tf'
      - '**.tfvars'

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureServiceConnection'

stages:
${envs.map(env => `  - stage: Deploy_${env}
    displayName: 'Deploy to ${env}'
    jobs:
      - deployment: deploy
        environment: '${env}'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@1
                  inputs:
                    terraformVersion: '1.9.0'
                - task: TerraformCLI@2
                  displayName: 'Terraform Init'
                  inputs:
                    command: init
                    workingDirectory: '$(System.DefaultWorkingDirectory)'
                    backendType: azurerm
                - task: TerraformCLI@2
                  displayName: 'Terraform Plan'
                  inputs:
                    command: plan
                    workingDirectory: '$(System.DefaultWorkingDirectory)'
                    commandOptions: '-var-file=environments/${env}.tfvars'
                    environmentServiceName: '$(azureServiceConnection)'
                - task: TerraformCLI@2
                  displayName: 'Terraform Apply'
                  inputs:
                    command: apply
                    workingDirectory: '$(System.DefaultWorkingDirectory)'
                    commandOptions: '-var-file=environments/${env}.tfvars -auto-approve'
                    environmentServiceName: '$(azureServiceConnection)'`).join('\n')}
`;
}

// ─── Helpers ──────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function envShort(env: string): string {
  if (env === 'production') return 'prod';
  if (env === 'development') return 'dev';
  return env;
}

/** Guess a subnet prefix given the VNet address space and subnet index */
function guessSubnetPrefix(vnetAddressSpace: string, index: number): string {
  const parts = vnetAddressSpace.split('/')[0].split('.');
  return `${parts[0]}.${parts[1]}.${index}.0/24`;
}
