/**
 * Bicep Generator
 *
 * Generates a complete set of Bicep files from an Architecture object,
 * using Azure Verified Modules where available.
 */

import type { Architecture } from '../../schema/types.js';
import type { IaCExportOptions, GeneratedFile, IaCExportResult, IaCResource, IaCModule, IaCOutput } from '../types.js';
import { mapArchitectureToResources, groupResourcesIntoModules } from '../resource-mapper.js';
import { AVM_BICEP_MODULES, ARM_API_VERSIONS, hasAvmBicepModule } from './avm-registry.js';
import { generateBicepParams } from './param-generator.js';
import { RESOURCES } from '../../schema/resources.js';

/** Quick lookup from resource type key to ARM resource type string */
const RESOURCES_LOOKUP: Record<string, string> = Object.fromEntries(
  Object.entries(RESOURCES).map(([key, def]) => [key, def.type])
);

/** Track VNet address space allocation to avoid overlaps */
let vnetAddressCounter = 0;

export function generateBicep(arch: Architecture, options: IaCExportOptions): IaCExportResult {
  vnetAddressCounter = 0; // Reset per export
  const resources = mapArchitectureToResources(arch);
  const modules = groupResourcesIntoModules(resources);

  const files: GeneratedFile[] = [];
  let resourceCount = 0;
  let moduleCount = 0;

  // 1. Generate main.bicep
  files.push({
    path: 'main.bicep',
    content: generateMainBicep(arch, modules, options),
    description: 'Main orchestration file — deploys all modules at subscription scope',
  });

  // 2. Generate module files
  for (const mod of modules) {
    const moduleContent = generateModuleBicep(mod, modules, options);
    files.push({
      path: `modules/${mod.name}.bicep`,
      content: moduleContent,
      description: `${capitalize(mod.name)} module — ${mod.resources.length} resource(s)`,
    });
    resourceCount += mod.resources.length;
    moduleCount++;
  }

  // 3. Generate parameter files for each environment
  for (const env of options.environments) {
    const paramFiles = generateBicepParams(modules, env, options);
    files.push(...paramFiles);
  }

  // 4. Generate CI/CD pipeline if requested
  if (options.includePipeline === 'github-actions') {
    files.push({
      path: '.github/workflows/deploy-bicep.yml',
      content: generateGitHubActionsBicep(options),
      description: 'GitHub Actions workflow for Bicep deployment',
    });
  } else if (options.includePipeline === 'azure-devops') {
    files.push({
      path: 'azure-pipelines.yml',
      content: generateAzureDevOpsBicep(options),
      description: 'Azure DevOps pipeline for Bicep deployment',
    });
  }

  return {
    files,
    summary: {
      totalFiles: files.length,
      resourceCount,
      moduleCount,
      format: 'bicep',
    },
  };
}

// ─── Main Bicep ───────────────────────────────────────────────────

/**
 * Compute the set of dependency params that a module actually needs.
 * Rather than passing ALL outputs from dependency modules, only pass those
 * that the module's resources are likely to reference (based on resource types).
 */
function computeNeededDepParams(mod: IaCModule, allModules: IaCModule[]): Set<string> {
  const needed = new Set<string>();

  for (const depModName of mod.dependsOnModules) {
    const depMod = allModules.find(m => m.name === depModName);
    if (!depMod) continue;

    // Only include outputs that are actually referenced by resources in this module
    for (const r of mod.resources) {
      for (const depId of r.dependsOn) {
        const depRes = depMod.resources.find(dr => dr.identifier === depId);
        if (depRes) {
          // Find the matching output(s) for this dependency resource
          for (const out of depMod.outputs) {
            if (out.name.startsWith(depRes.identifier)) {
              needed.add(`${depModName}_${out.name}`);
            }
          }
        }
      }
    }
  }

  return needed;
}

function generateMainBicep(arch: Architecture, modules: IaCModule[], options: IaCExportOptions): string {
  const lines: string[] = [];

  lines.push('targetScope = \'subscription\'');
  lines.push('');

  // Metadata
  lines.push(`metadata name = '${sanitizeBicepString(arch.title || 'Architecture Deployment')}'`);
  lines.push(`metadata description = '${sanitizeBicepString(arch.description || 'Generated by AI Architecture Generator')}'`);
  lines.push('');

  // Parameters
  lines.push('@description(\'Primary deployment region\')');
  lines.push('param location string');
  lines.push('');
  lines.push('@description(\'Environment name\')');
  lines.push('@allowed([');
  lines.push('  \'prod\'');
  lines.push('  \'dev\'');
  lines.push('  \'staging\'');
  lines.push('])');
  lines.push('param environment string');
  lines.push('');
  lines.push('@description(\'Resource name prefix\')');
  lines.push('param prefix string = \'\'');
  lines.push('');
  lines.push('@description(\'Tags to apply to all resources\')');
  lines.push('param tags object = {');
  lines.push('  environment: environment');
  lines.push(`  project: '${sanitizeBicepString(arch.title || 'architecture')}'`);
  lines.push('  managedBy: \'bicep\'');
  lines.push('}');
  lines.push('');

  // Resource Group
  lines.push('// Resource Group');
  lines.push('resource rg \'Microsoft.Resources/resourceGroups@2024-03-01\' = {');
  lines.push('  name: \'rg-${prefix}${environment}\'');
  lines.push('  location: location');
  lines.push('  tags: tags');
  lines.push('}');
  lines.push('');

  // Module deployments
  for (const mod of modules) {
    const neededParams = computeNeededDepParams(mod, modules);
    const depModules = mod.dependsOnModules.filter(d => modules.some(m => m.name === d));

    lines.push(`// ${capitalize(mod.name)}`);
    lines.push(`module ${mod.name} './modules/${mod.name}.bicep' = {`);
    lines.push(`  name: '${mod.name}-\${environment}'`);
    lines.push('  scope: rg');
    lines.push('  params: {');
    lines.push('    location: location');
    lines.push('    environment: environment');
    lines.push('    prefix: prefix');
    lines.push('    tags: tags');

    // Pass outputs from dependency modules — only those the module needs
    for (const depMod of depModules) {
      const dep = modules.find(m => m.name === depMod);
      if (dep) {
        for (const out of dep.outputs) {
          const paramName = `${depMod}_${out.name}`;
          if (neededParams.has(paramName)) {
            lines.push(`    ${paramName}: ${depMod}.outputs.${out.name}`);
          }
        }
      }
    }

    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  // Outputs
  lines.push('// ==================== Outputs ====================');
  lines.push('');
  lines.push('output resourceGroupName string = rg.name');
  lines.push('output resourceGroupId string = rg.id');
  for (const mod of modules) {
    for (const out of mod.outputs.slice(0, 3)) {
      lines.push(`output ${mod.name}_${out.name} string = ${mod.name}.outputs.${out.name}`);
    }
  }

  return lines.join('\n');
}

// ─── Module Bicep ─────────────────────────────────────────────────

function generateModuleBicep(mod: IaCModule, allModules: IaCModule[], options: IaCExportOptions): string {
  const lines: string[] = [];

  // Filter out subnet resources — they'll be inlined in VNet definitions
  const effectiveResources = mod.resources.filter(r => r.resourceType !== 'subnet');

  // Parameters
  lines.push('@description(\'Deployment region\')');
  lines.push('param location string');
  lines.push('');
  lines.push('@description(\'Environment name\')');
  lines.push('param environment string');
  lines.push('');
  lines.push('@description(\'Resource name prefix\')');
  lines.push('param prefix string = \'\'');
  lines.push('');
  lines.push('@description(\'Tags\')');
  lines.push('param tags object = {}');
  lines.push('');

  // Dependency params — only declare params that are actually needed by this module
  const neededParams = computeNeededDepParams(mod, allModules);
  for (const depModName of mod.dependsOnModules) {
    const depMod = allModules.find(m => m.name === depModName);
    if (!depMod) continue;
    for (const out of depMod.outputs) {
      const paramName = `${depModName}_${out.name}`;
      if (neededParams.has(paramName)) {
        lines.push(`@description('${sanitizeBicepString(out.description)}')`);
        lines.push(`param ${paramName} string = ''`);
        lines.push('');
      }
    }
  }

  // Resources
  for (const r of effectiveResources) {
    lines.push(`// ${r.name}`);

    if (options.useAVM && hasAvmBicepModule(r.resourceType)) {
      lines.push(...generateAvmModuleCall(r, mod, allModules));
    } else {
      lines.push(...generateRawResourceDeclaration(r));
    }
    lines.push('');
  }

  // Outputs — only for effective resources (not subnets)
  const effectiveOutputs = mod.outputs.filter(out => {
    // Check if this output belongs to a subnet resource
    const subnetRes = mod.resources.find(r => r.resourceType === 'subnet' && out.name.startsWith(r.identifier));
    return !subnetRes;
  });

  lines.push('// ==================== Outputs ====================');
  lines.push('');
  for (const out of effectiveOutputs) {
    lines.push(`@description('${sanitizeBicepString(out.description)}')`);
    lines.push(`output ${out.name} string = ${out.value}`);
    lines.push('');
  }

  return lines.join('\n');
}

function generateAvmModuleCall(r: IaCResource, currentModule: IaCModule, allModules: IaCModule[]): string[] {
  const lines: string[] = [];
  const avmRef = AVM_BICEP_MODULES[r.resourceType]!;

  lines.push(`module ${r.identifier} '${avmRef.module}' = {`);
  lines.push(`  name: '${r.identifier}-\${uniqueString(deployment().name)}'`);
  lines.push('  params: {');
  lines.push(`    name: '\${prefix}${r.iacName}-\${environment}'`);

  // Location param
  if (avmRef.requiredParams.includes('location')) {
    lines.push('    location: location');
  }

  // Tags
  lines.push('    tags: tags');

  // Type-specific params
  generateTypeSpecificParams(r, lines, currentModule, allModules);

  lines.push('  }');
  lines.push('}');

  return lines;
}

function generateTypeSpecificParams(r: IaCResource, lines: string[], currentModule: IaCModule, allModules: IaCModule[]): void {
  // Helper to find a resource within the same module
  const findInModule = (type: string) => currentModule.resources.find(res => res.resourceType === type);
  // Helper to find a VNet in the same module
  const findVNet = () => findInModule('hubVnet') || findInModule('vnet');
  // Helper to find a param from dependency modules
  const findDepParam = (resourceType: string, suffix: string = 'Id') => {
    for (const depModName of currentModule.dependsOnModules) {
      const depMod = allModules.find(m => m.name === depModName);
      if (!depMod) continue;
      const depRes = depMod.resources.find(res => res.resourceType === resourceType);
      if (depRes) {
        return `${depModName}_${depRes.identifier}${suffix}`;
      }
    }
    return null;
  };

  // Helper to resolve Log Analytics workspace reference
  const resolveLogAnalyticsRef = (): string => {
    const localLaw = findInModule('logAnalytics');
    if (localLaw) return `${localLaw.identifier}.outputs.resourceId`;
    const depParam = findDepParam('logAnalytics');
    if (depParam) return depParam;
    return '\'\' // TODO: Reference Log Analytics workspace resource ID';
  };

  switch (r.resourceType) {
    case 'vm':
      lines.push('    vmSize: \'Standard_D2s_v5\'');
      lines.push('    zone: 1');
      lines.push('    osType: \'Linux\'');
      lines.push('    imageReference: {');
      lines.push('      publisher: \'Canonical\'');
      lines.push('      offer: \'ubuntu-24_04-lts\'');
      lines.push('      sku: \'server\'');
      lines.push('      version: \'latest\'');
      lines.push('    }');
      lines.push('    osDisk: {');
      lines.push('      diskSizeGB: 128');
      lines.push('      managedDisk: { storageAccountType: \'Premium_LRS\' }');
      lines.push('    }');
      lines.push('    adminUsername: \'azureuser\'');
      lines.push('    disablePasswordAuthentication: true');
      lines.push('    publicKeys: [');
      lines.push('      // TODO: Add your SSH public key');
      lines.push('      // { keyData: \'ssh-rsa AAAA...\', path: \'/home/azureuser/.ssh/authorized_keys\' }');
      lines.push('    ]');
      lines.push('    nicConfigurations: [');
      lines.push('      {');
      lines.push('        ipConfigurations: [');
      {
        const subnetParam = findDepParam('vnet', 'DefaultSubnetId') || findDepParam('hubVnet', 'DefaultSubnetId');
        const subnetRef = subnetParam || '\'\' // TODO: Reference subnet resource ID';
        lines.push(`          { subnetResourceId: ${subnetRef} }`);
      }
      lines.push('        ]');
      lines.push('      }');
      lines.push('    ]');
      break;
    case 'aks':
      lines.push('    primaryAgentPoolProfiles: [');
      lines.push('      {');
      lines.push('        name: \'system\'');
      lines.push('        count: 3');
      lines.push('        vmSize: \'Standard_D4s_v5\'');
      lines.push('        mode: \'System\'');
      lines.push('        osType: \'Linux\'');
      lines.push('      }');
      lines.push('    ]');
      break;
    case 'appService':
    case 'functionApp':
      lines.push(`    kind: '${r.resourceType === 'functionApp' ? 'functionapp,linux' : 'app,linux'}'`);
      {
        const aspLocal = findInModule('appServicePlan');
        const aspRef = aspLocal
          ? `${aspLocal.identifier}.outputs.resourceId`
          : (findDepParam('appServicePlan') || '\'\' // TODO: Reference App Service Plan resource ID');
        lines.push(`    serverFarmResourceId: ${aspRef}`);
      }
      break;
    case 'containerApp':
      {
        const caeLocal = findInModule('containerAppEnv');
        const caeRef = caeLocal
          ? `${caeLocal.identifier}.outputs.resourceId`
          : (findDepParam('containerAppEnv') || '\'\' // TODO: Reference Container App Environment resource ID');
        lines.push(`    environmentResourceId: ${caeRef}`);
      }
      lines.push('    containers: [');
      lines.push('      {');
      lines.push(`        name: '${r.iacName}'`);
      lines.push('        image: \'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest\'');
      lines.push('        resources: { cpu: json(\'0.5\'), memory: \'1Gi\' }');
      lines.push('      }');
      lines.push('    ]');
      break;
    case 'containerAppEnv':
      lines.push(`    logAnalyticsWorkspaceResourceId: ${resolveLogAnalyticsRef()}`);
      break;
    case 'vnet':
    case 'hubVnet': {
      // Use architecture-provided address space or allocate unique one
      const addressSpace = r.addressSpace || r.properties?.addressSpace as string || `10.${vnetAddressCounter++}.0.0/16`;
      lines.push(`    addressPrefixes: [ '${addressSpace}' ]`);

      // Inline subnets from architecture
      const subnets = r.architectureSubnets;
      if (subnets && subnets.length > 0) {
        lines.push('    subnets: [');
        for (const s of subnets) {
          const prefix = s.addressPrefix || guessSubnetPrefix(addressSpace, subnets.indexOf(s));
          lines.push('      {');
          lines.push(`        name: '${s.name}'`);
          lines.push(`        addressPrefix: '${prefix}'`);
          lines.push('      }');
        }
        lines.push('    ]');
      } else {
        // Default subnet
        const base = addressSpace.split('/')[0].split('.').slice(0, 2).join('.');
        lines.push('    subnets: [');
        lines.push('      {');
        lines.push('        name: \'default\'');
        lines.push(`        addressPrefix: '${base}.0.0/24'`);
        lines.push('      }');
        lines.push('    ]');
      }
      break;
    }
    case 'firewall':
      lines.push('    azureSkuTier: \'Standard\'');
      {
        const vnet = findVNet();
        if (vnet) {
          lines.push(`    virtualNetworkResourceId: ${vnet.identifier}.outputs.resourceId`);
        }
      }
      break;
    case 'bastion':
      {
        const vnet = findVNet();
        const vnetRef = vnet
          ? `${vnet.identifier}.outputs.resourceId`
          : (findDepParam('vnet') || findDepParam('hubVnet') || '\'\' // TODO: Reference VNet resource ID');
        lines.push(`    virtualNetworkResourceId: ${vnetRef}`);
      }
      break;
    case 'vpnGateway':
      lines.push('    gatewayType: \'Vpn\'');
      lines.push('    skuName: \'VpnGw1AZ\'');
      lines.push('    clusterSettings: {');
      lines.push('      clusterMode: \'activeActiveNoBgp\'');
      lines.push('    }');
      {
        const vnet = findVNet();
        if (vnet) {
          lines.push(`    vNetResourceId: ${vnet.identifier}.outputs.resourceId`);
        }
      }
      break;
    case 'openAI':
      lines.push('    kind: \'OpenAI\'');
      lines.push('    sku: \'S0\'');
      break;
    case 'cognitiveServices':
      lines.push('    kind: \'CognitiveServices\'');
      lines.push('    sku: \'S0\'');
      break;
    case 'storageAccount':
      lines.push('    skuName: \'Standard_LRS\'');
      lines.push('    kind: \'StorageV2\'');
      break;
    case 'cosmosDb':
      lines.push('    databaseAccountOfferType: \'Standard\'');
      lines.push('    locations: [');
      lines.push('      { locationName: location, failoverPriority: 0 }');
      lines.push('    ]');
      break;
    case 'sqlServer':
      lines.push('    administratorLogin: \'sqladmin\'');
      lines.push('    administratorLoginPassword: \'\' // TODO: Use Key Vault reference');
      break;
    case 'redis':
      lines.push('    skuName: \'Standard\'');
      lines.push('    capacity: 1');
      break;
    case 'keyVault':
      lines.push('    enableRbacAuthorization: true');
      break;
    case 'serviceBus':
      lines.push('    skuObject: { name: \'Standard\' }');
      break;
    case 'logAnalytics':
      lines.push('    skuName: \'PerGB2018\'');
      lines.push('    dataRetention: 30');
      break;
    case 'appInsights':
      lines.push(`    workspaceResourceId: ${resolveLogAnalyticsRef()}`);
      lines.push('    kind: \'web\'');
      break;
    case 'loadBalancer':
      lines.push('    frontendIPConfigurations: [');
      lines.push('      { name: \'default\' }');
      lines.push('    ]');
      break;
    case 'apiManagement':
      lines.push('    publisherEmail: \'admin@contoso.com\' // TODO: Update email');
      lines.push('    publisherName: \'Contoso\' // TODO: Update org name');
      break;
    case 'machineLearning':
      lines.push('    sku: \'Basic\'');
      break;
    case 'databricks':
      lines.push('    sku: \'premium\'');
      break;
  }
}

/** Guess a subnet prefix given the VNet address space and subnet index */
function guessSubnetPrefix(vnetAddressSpace: string, index: number): string {
  const parts = vnetAddressSpace.split('/')[0].split('.');
  return `${parts[0]}.${parts[1]}.${index}.0/24`;
}

function generateRawResourceDeclaration(r: IaCResource): string[] {
  const lines: string[] = [];

  // Look up ARM resource type
  const resDef = RESOURCES_LOOKUP[r.resourceType];
  const armType = resDef || `Microsoft.Resources/${r.resourceType}`;
  const apiVersion = ARM_API_VERSIONS[armType] || '2024-01-01';

  lines.push(`// TODO: AVM module not yet available for ${r.resourceType} — using raw resource declaration`);
  lines.push(`resource ${r.identifier} '${armType}@${apiVersion}' = {`);
  lines.push(`  name: '\${prefix}${r.iacName}-\${environment}'`);

  // Child resources (subnets) don't support top-level location/tags
  const isChildResource = armType.split('/').length > 2;
  if (!isChildResource) {
    lines.push('  location: location');
    lines.push('  tags: tags');
  }
  lines.push('  properties: {}');
  lines.push('}');

  return lines;
}

// ─── CI/CD Pipelines ──────────────────────────────────────────────

function generateGitHubActionsBicep(options: IaCExportOptions): string {
  const envs = options.environments.map(e => e === 'production' ? 'prod' : e === 'development' ? 'dev' : 'staging');
  return `name: Deploy Bicep Infrastructure
on:
  push:
    branches: [main]
    paths:
      - '**.bicep'
      - '**.bicepparam'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: '${envs[0]}'
        type: choice
        options:
${envs.map(e => `          - ${e}`).join('\n')}

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate Bicep
        run: az deployment sub validate --location westeurope --template-file main.bicep --parameters main.\${{ inputs.environment || '${envs[0]}' }}.bicepparam

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    environment: \${{ inputs.environment || '${envs[0]}' }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy
        run: |
          az deployment sub create \\
            --location westeurope \\
            --template-file main.bicep \\
            --parameters main.\${{ inputs.environment || '${envs[0]}' }}.bicepparam
`;
}

function generateAzureDevOpsBicep(options: IaCExportOptions): string {
  const envs = options.environments.map(e => e === 'production' ? 'prod' : e === 'development' ? 'dev' : 'staging');
  return `trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**.bicep'
      - '**.bicepparam'

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureServiceConnection'
  location: 'westeurope'

stages:
${envs.map(env => `  - stage: Deploy_${env}
    displayName: 'Deploy to ${env}'
    jobs:
      - deployment: deploy
        environment: '${env}'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: 'Validate Bicep'
                  inputs:
                    azureSubscription: \$(azureServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment sub validate \\
                        --location \$(location) \\
                        --template-file main.bicep \\
                        --parameters main.${env}.bicepparam
                - task: AzureCLI@2
                  displayName: 'Deploy Bicep'
                  inputs:
                    azureSubscription: \$(azureServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment sub create \\
                        --location \$(location) \\
                        --template-file main.bicep \\
                        --parameters main.${env}.bicepparam`).join('\n')}
`;
}

// ─── Helpers ──────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function sanitizeBicepString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
