/**
 * Bicep Parameter Generator
 *
 * Generates .bicepparam files for each environment with smart defaults:
 * - Development: smaller SKUs, single instance
 * - Staging: moderate SKUs, basic HA
 * - Production: production SKUs, full HA configuration
 */

import type { GeneratedFile, IaCModule, IaCExportOptions } from '../types.js';

interface EnvProfile {
  shortName: string;
  location: string;
  vmSize: string;
  aksNodeCount: number;
  aksVmSize: string;
  sqlSku: string;
  redisSku: string;
  redisCapacity: number;
  storageSku: string;
  appServiceSku: string;
  apimSku: string;
  logRetentionDays: number;
  firewallTier: string;
  serviceBusSku: string;
  eventHubSku: string;
  keyVaultSku: string;
  cosmosDbConsistency: string;
  zones: string;
}

const ENV_PROFILES: Record<string, EnvProfile> = {
  development: {
    shortName: 'dev',
    location: 'westeurope',
    vmSize: 'Standard_B2s',
    aksNodeCount: 1,
    aksVmSize: 'Standard_B4ms',
    sqlSku: 'Basic',
    redisSku: 'Basic',
    redisCapacity: 0,
    storageSku: 'Standard_LRS',
    appServiceSku: 'B1',
    apimSku: 'Developer',
    logRetentionDays: 30,
    firewallTier: 'Standard',
    serviceBusSku: 'Basic',
    eventHubSku: 'Basic',
    keyVaultSku: 'standard',
    cosmosDbConsistency: 'Session',
    zones: '[]',
  },
  staging: {
    shortName: 'staging',
    location: 'westeurope',
    vmSize: 'Standard_D2s_v5',
    aksNodeCount: 2,
    aksVmSize: 'Standard_D4s_v5',
    sqlSku: 'S1',
    redisSku: 'Standard',
    redisCapacity: 1,
    storageSku: 'Standard_GRS',
    appServiceSku: 'S1',
    apimSku: 'Basic',
    logRetentionDays: 60,
    firewallTier: 'Standard',
    serviceBusSku: 'Standard',
    eventHubSku: 'Standard',
    keyVaultSku: 'standard',
    cosmosDbConsistency: 'BoundedStaleness',
    zones: '[1, 2]',
  },
  production: {
    shortName: 'prod',
    location: 'westeurope',
    vmSize: 'Standard_D4s_v5',
    aksNodeCount: 3,
    aksVmSize: 'Standard_D8s_v5',
    sqlSku: 'P1',
    redisSku: 'Premium',
    redisCapacity: 1,
    storageSku: 'Standard_ZRS',
    appServiceSku: 'P1v3',
    apimSku: 'Standard',
    logRetentionDays: 90,
    firewallTier: 'Premium',
    serviceBusSku: 'Premium',
    eventHubSku: 'Standard',
    keyVaultSku: 'premium',
    cosmosDbConsistency: 'Strong',
    zones: '[1, 2, 3]',
  },
};

export function generateBicepParams(
  modules: IaCModule[],
  environment: 'production' | 'development' | 'staging',
  _options: IaCExportOptions,
): GeneratedFile[] {
  const profile = ENV_PROFILES[environment];
  const files: GeneratedFile[] = [];

  const lines: string[] = [];
  lines.push(`using 'main.bicep'`);
  lines.push('');
  lines.push(`// Environment: ${environment}`);
  lines.push(`// Generated by AI Architecture Generator`);
  lines.push('');
  lines.push(`param location = '${profile.location}'`);
  lines.push(`param environment = '${profile.shortName}'`);
  lines.push(`param prefix = ''`);
  lines.push('');
  lines.push('param tags = {');
  lines.push(`  environment: '${profile.shortName}'`);
  lines.push(`  managedBy: 'bicep'`);
  lines.push('}');

  files.push({
    path: `main.${profile.shortName}.bicepparam`,
    content: lines.join('\n'),
    description: `Parameter file for ${environment} environment`,
  });

  return files;
}
